travis:
  secure:
    BINSTAR_TOKEN: D3unxj1kD7U8/cObsY0b9DhPS4bwOSPMzY3pgMfTxovLd5ktfxp3+YlZsq2aQlm2ba2udy8JKnXw6NE3TaLfsQdrMjggwPy6YGjujcucln6SI7iiIlUdRkCVGSdUB6uOWhtOsiuZ36xV2rqyPUELg9vvKEEpq/0vLdO7UV4D6d+Gu3WWXJnm1bDD04oS8pkDj2YuXjo6azfdGO+Wdh8SH/0lT3wEGoPBJx9z6Ml+xS+U91LzMqjB4nYWGEI/b0iRSfc3iq4TkZ1QzSWrFdJgG6/1cQsAg+eAehJU6JcoZgnVr+WZvsz6/w6lAIq5CwH0QjfDJ44ISbc0PiWC3uE4Dn2oSWHGvX65D4UDaRpZCC8eXEKVGT77U2yv6TFmtNjmWq6TW2KQ1sV4X0ROxnUgHZgkD2RhzyfEDYmn5Ba6wbO/umLEY7wl16weANzvzEmD1AqWNTIaJtB1vly4vfDTXwyED395EYLQVGxJb0sRebcSfncyueG7MknRyV8gfaO/XX8QFUEP4vTOHs6mkoC3SlIpmzDaSt2C68VhCGv8tk9wF1RjbMRMj6KGxozhsDpZskXGSpVUdiRyyqgh0maKrvizT2O0djKIfGWgFeg9/LTZXHxb6D6CGHmJIOq+FdMOeSlwlvFyi6d7B9g8CuTjkCNkHeKJmW3L60tDYhpN9I4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
